name: Update Repositories List

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
  schedule:
    - cron: "0 1 * * *" # Update everyday

permissions:
  contents: write

jobs:
  update-repos-list:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      - name: Install uv and restore cache
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.7.17"
          enable-cache: true
          cache-dependency-glob: "**/pyproject.toml"

      - name: Install Dependencies
        run: uv sync

      - name: Update Repositories List
        run: uv run scripts/fetch_repos.py
        env:
          PERSONAL_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ORG_NAME: HITSZ-OpenAuto

      - name: Commit and Push Changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

          git add .
          
          # Check if there are any changes to commit
          if git diff --staged --quiet; then
            echo "No changes detected. Skipping commit and push."
          else
            echo "Changes detected. Committing and pushing..."
            git commit -m "ci: update repositories list [automated]"
            git push origin HEAD:main
          fi
          
